{
 "title": "Fleet - Glance",
 "description": "At-a glance fleet health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UpDown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=\"node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory available %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes{job=\"node\"} / node_memory_MemTotal_bytes{job=\"node\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Disk Used %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Boot Disk Used %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - node_filesystem_avail_bytes{mountpoint=\"/boot\"} / node_filesystem_size_bytes{mountpoint=\"/boot\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Units",
   "type": "stat",
   "description": "Systemd units in state failed.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_systemd_units{state=\"failed\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}